apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: random-apps
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/grzesiek2115/argocd-playground/apps'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'