# https://kind.sigs.k8s.io/docs/user/configuration/

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: grzegorz-k8s-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 80
- role: worker
- role: worker